### ISSUE TITLE
not work on Unity 5.3.1f1 OS X

### ISSUE THREAD

**Issue by yunoshev** [consulo/UnityEditorConsuloPlugin#1]
Plugin added to project, "Edit/Use Consulo as External Editor" - enabled

When you click on a С# file in the project - Mono Develop open and couple follow exception at console

```
SocketException: Connection refused
System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP, Boolean requireSocketPolicy)
System.Net.WebConnection.Connect (System.Net.HttpWebRequest request)
Rethrow as WebException: Error: ConnectFailure (Connection refused)
System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult)
System.Net.HttpWebRequest.GetRequestStream ()
MustBe.Consulo.Internal.ConsuloPlugin.OnOpenedAssetCallback (Int32 instanceID, Int32 line)
UnityEditor.DockArea:OnGUI()
```

**Comment by VISTALL** [comment]
Consulo opened? For now its known limitation (sorry)

**Comment by yunoshev** [comment]
I try both cases - Consulo already launched (at select project screen) and not launched - same issue

**Comment by VISTALL** [comment]
Please say Consulo build and Unity plugin build numbers?

![](http://klikr.org/72068a5217dbed2f863aa206a1a4.png)

Here you can get plugin build

**Comment by yunoshev** [comment]
Unity3D Plugin Version 2081
Consulo 1.0 #1266, Build #1266, built on January 2, 2016, JDK: 1.8.0_25, VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Unity3D version 5.3.1f1
OS X version 10.11.2

**Comment by VISTALL** [comment]
Try to open in browser URL (with started Consulo)

http://localhost:62242/startTime

Please say what u see)

**Comment by yunoshev** [comment]
at follow screen https://monosnap.com/file/enKVB6YW9eqvm1uf0MKWkIE9C0ADjO  -> GET http://localhost:62242/startTime net::ERR_CONNECTION_REFUSED
I create and open test empty project - in this case - build-in http server return unix time

But in this case, if I click on C# file in Unity Editor - nothing happens. No errors on Unity console, no changes with Consulo (still test project open).

**Comment by VISTALL** [comment]
Try to import Unity project, and then try to double click in Editor

**Comment by VISTALL** [comment]
I think you need Import Project and then select file in Unity Editor.


I already working on improving.

 * port is not binded until project is opened (bug)
 * need open project if it imported (feature)
 * need call Import Project - if not imported (for now idk)

**Comment by VISTALL** [comment]
I have improved opening, but for now need manually call Import project (once)

**Comment by VISTALL** [comment]
Need update Consulo & Unity plugin after one hour

**Comment by VISTALL** [comment]
Added support for auto-import project on double click. Only required opened Consulo.

But need last builds

**Comment by VISTALL** [comment]
Actual?

**Comment by VISTALL** [comment]
If repeated, create new issue
