### ISSUE TITLE
TypeLoadException: Could not load type 'UnityEditor.Menu' from assembly 'UnityEditorConsuloPlugin'.

### ISSUE THREAD

**Issue by rganeyev** [consulo/UnityEditorConsuloPlugin#2]
I copied UnityEditorConsuloPlugin to Assets/Editor/Plugins/ folder. Now I have an option "Use Consule as External Editor" disabled.

When I try to select it, I have an error: "TypeLoadException: Could not load type 'UnityEditor.Menu' from assembly 'UnityEditorConsuloPlugin'."

Using Unity 4.6.9p3.

**Comment by VISTALL** [comment]
For 4.6 Unity need another library

**Comment by rganeyev** [comment]
My bad. Closing task.
