### ISSUE TITLE
Cannot perform upm operation In Package Manager

### ISSUE THREAD

**Issue by parmaia** [consulo/UnityEditorConsuloPlugin#24]
After register Consulo plugin in manifest, I open the Package Manager and in the bottom there is this error message:

_Error loading packages, see console_

In the console, there is this error:

_Cannot perform upm operation: Request [GET https://upm.consulo.io/-/v1/search?text=com.consulo&from=0&size=250] failed. 
One or more invalid parameters was given. [InvalidParameter]_

Followed by:

_Error searching for packages._

Followed by this message (not marked as error):

_[PackageManager] Error Request [GET https://upm.consulo.io/-/v1/search?text=com.consulo&from=0&size=250] failed. One or more invalid parameters was given._

The result is that Consulo plugin works well, but Unity can't load all the packages in the Package Manager.

![image](https://user-images.githubusercontent.com/2512986/101789858-100a0e80-3b02-11eb-887f-875ad49986bb.png)

If I remove the Consulo code from the manifest, unity load the packages list without any problem.

I'm using Unity 2019.4.10f1, Consulo 2020.11 and Windows 10.

This is the content of the manifest.json:

```
{
  "scopedRegistries": [
    {
      "name": "consulo.io",
      "url": "https://upm.consulo.io/",
      "scopes": [
        "com.consulo"
      ]
    }
  ],
  "dependencies": {
    "com.consulo.ide": "2.4.0"
  }
}
```

I tested with 2.2.0, 2.3.0 and 2.4.0 in the dependencies. (2.2.0 is what Consulo adds to the manifest).

Just to add more info (not sure if relevant), if I run:

`curl "https://upm.consulo.io/-/v1/search?text=com.consulo&from=0&size=250" `

I get this response:

```
<!DOCTYPE html>
<html>
<head>
  <title>400 - Nexus Repository Manager</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>


  <!--[if lt IE 9]>
  <script>(new Image).src="https://upm.consulo.io/favicon.ico?3.6.2-01"</script>
  <![endif]-->
  <link rel="icon" type="image/png" href="https://upm.consulo.io/favicon-32x32.png?3.6.2-01" sizes="32x32">
  <link rel="mask-icon" href="https://upm.consulo.io/safari-pinned-tab.svg?3.6.2-01" color="#5bbad5">
  <link rel="icon" type="image/png" href="https://upm.consulo.io/favicon-16x16.png?3.6.2-01" sizes="16x16">
  <link rel="shortcut icon" href="https://upm.consulo.io/favicon.ico?3.6.2-01">
  <meta name="msapplication-TileImage" content="https://upm.consulo.io/mstile-144x144.png?3.6.2-01">
  <meta name="msapplication-TileColor" content="#00a300">

  <link rel="stylesheet" type="text/css" href="https://upm.consulo.io/static/css/nexus-content.css?3.6.2-01"/>
</head>
<body>
<div class="nexus-header">
  <a href="https://upm.consulo.io">
    <div class="product-logo">
      <img src="https://upm.consulo.io/static/images/nexus.png?3.6.2-01"/>
    </div>
    <div class="product-id">
      <div class="product-id__line-1">
        <span class="product-name">Nexus Repository Manager</span>
      </div>
      <div class="product-id__line-2">
        <span class="product-spec">OSS 3.6.2-01</span>
      </div>
    </div>
  </a>
</div>

<div class="nexus-body">
  <div class="content-header">
    <img src="https://upm.consulo.io/static/rapture/resources/icons/x32/exclamation.png?3.6.2-01"/>
    <span class="title">Error 400</span>
    <span class="description">Bad Request</span>
  </div>
  <div class="content-body">
    <div class="content-section">
      Bad Request
    </div>
      </div>
</div>
</body>
</html>
```

**Comment by VISTALL** [comment]
Hello. There same issues exists in another repo, and I moved it this repo. And answer in that issue https://github.com/consulo/UnityEditorConsuloPlugin/issues/25

Duplicate.

Thanks:)
