### ISSUE TITLE
Consulo -> UnityEditor communication

### ISSUE THREAD

**Issue by VISTALL** [consulo/UnityEditorConsuloPlugin#3]
For now, Unity can only send to Consulo some data(for example opening file). But consulo cant send it to Unity.

We need it for Testing support & Opening Scene via linemarker

**Comment by cupsster** [comment]
I opened new issue on Consulo repo but I think it should be here because I suspect this plugin is causing it. Please look at it.

**Comment by VISTALL** [comment]
This issue already fixed, i forgot to close it
