### ISSUE TITLE
Error opening a Scene in Unity if Consulo is not open.

### ISSUE THREAD

**Issue by rogeratplumbee** [consulo/UnityEditorConsuloPlugin#4]
If you open a Scene in unity when Consulo is not running, the attached image popup appears.
<img width="473" alt="screen shot 2016-07-04 at 21 04 41" src="https://cloud.githubusercontent.com/assets/5928367/16569171/1ead922e-422b-11e6-8b60-abf56558e05a.png">

**Comment by VISTALL** [comment]
Hi. It's a limitation of plugin. It can't start IDE for now

**Comment by rogeratplumbee** [comment]
I understand, but the plugin is blocking Unity, so I can't change the scene without opening Consulo. This error should not appear when I try to open a scene.

**Comment by VISTALL** [comment]
Can you update this plugin to last version? Looks like i already fixed this issue, and introduced new feature(console log)

**Comment by rogeratplumbee** [comment]
Sorted cheers! I missed that was a new version before posting the issue. Apologies.

**Comment by VISTALL** [comment]
Np. Due i don't implemented version check.
