### ISSUE TITLE
UnityEditorConsuloPlugin 4.6 - no option in menu

### ISSUE THREAD

**Issue by moozgoos** [consulo/UnityEditorConsuloPlugin#8]
Hi,
I'am using Unity 4.7.2f1. After adding UnityEditorConsuloPlugin [4.6 version] to Assets->Plugins folder i don't have _Use Consulo as External Editor_ option in _Edit_ menu.

**Comment by VISTALL** [comment]
You need just set Consulo as external script editor. 

(I forgot change README, Sorry)

Thanks

**Comment by VISTALL** [comment]
It helps?

**Comment by moozgoos** [comment]
Yeah, but dubble-clicking at some script error in Unity console, Consulo window still doesn't get focus...

**Comment by VISTALL** [comment]
Yeah. It's open problem https://github.com/consulo/consulo-unity3d/issues/81
